apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hzhh19nsf-python 
  janus-idp.io/tekton: hzhh19nsf-python
  backstage.io/kubernetes-id: hzhh19nsf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hzhh19nsf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml