apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hzhh19nsf-python
  janus-idp.io/tekton: hzhh19nsf-python
  backstage.io/kubernetes-id: hzhh19nsf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hzhh19nsf-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
