apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hzhh19nsf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hzhh19nsf-python 
  name: hzhh19nsf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hzhh19nsf-python 
