apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hzhh19nsf-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:4173abbc87fadac94d33aeb3e09a5432796898d9@sha256:dd593dfcbdd488c1beb2da4731570ab3363c2bcdd2803f5c851f8d9e958c7a55
          name: container-image
